### ISSUE TITLE
Couldn't make it work through tiled VAE 

### ISSUE THREAD

**Issue by aetherwu** [pkuliyi2015/sd-webui-stablesr#1]
Use MultiDiffusion in tiled VAE：
`Traceback (most recent call last):
  File "D:\ai\auto-ui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\ai\auto-ui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\ai\auto-ui\modules\img2img.py", line 180, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\ai\auto-ui\modules\scripts.py", line 408, in run
    processed = script.run(p, *script_args)
  File "D:\ai\auto-ui\extensions\sd-webui-stablesr\scripts\stablesr.py", line 231, in run
    result: Processed = processing.process_images(p)
  File "D:\ai\auto-ui\modules\processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "D:\ai\auto-ui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "D:\ai\auto-ui\modules\processing.py", line 680, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\ai\auto-ui\extensions\sd-webui-stablesr\scripts\stablesr.py", line 209, in sample_custom
    samples = sampler.sample(p, x, conditioning, unconditional_conditioning, image_conditioning=p.image_conditioning)
  File "D:\ai\auto-ui\modules\sd_samplers_kdiffusion.py", line 411, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\ai\auto-ui\modules\sd_samplers_kdiffusion.py", line 285, in launch_sampling
    return func()
  File "D:\ai\auto-ui\modules\sd_samplers_kdiffusion.py", line 411, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ai\auto-ui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ai\auto-ui\modules\sd_samplers_kdiffusion.py", line 169, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ai\auto-ui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 243, in wrapper
    return fn(*args, **kwargs)
  File "D:\ai\auto-ui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 103, in kdiff_forward
    return self.sample_one_step(x_in, org_func, repeat_func, custom_func)
  File "D:\ai\auto-ui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 179, in sample_one_step
    x_tile_out = repeat_func(x_tile, bboxes)
  File "D:\ai\auto-ui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 97, in repeat_func
    x_tile_out = self.sampler_forward(x_tile, sigma_in_tile, cond=new_cond)
  File "D:\ai\auto-ui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\ai\auto-ui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\ai\auto-ui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\ai\auto-ui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ai\auto-ui\extensions\sd-webui-stablesr\scripts\stablesr.py", line 92, in unet_forward
    return getattr(unet, FORWARD_CACHE_NAME)(x, timesteps, context, y, **kwargs)
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 82, in forward
    x = layer(x, emb)
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 249, in forward
    return checkpoint(
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\ai\auto-ui\extensions\sd-webui-stablesr\srmodule\spade.py", line 139, in <lambda>
    resblock._forward = lambda x, timesteps, resblock=resblock, spade=self.input_blocks[i]: dual_resblock_forward(resblock, x, timesteps, spade, get_struct_cond)
  File "D:\ai\auto-ui\extensions\sd-webui-stablesr\srmodule\spade.py", line 80, in dual_resblock_forward
    h = spade(h, get_struct_cond())
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ai\auto-ui\extensions\sd-webui-stablesr\srmodule\spade.py", line 34, in forward
    return checkpoint(
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\ai\auto-ui\extensions\sd-webui-stablesr\srmodule\spade.py", line 39, in _forward
    segmap = segmap_dic[str(x_dic.size(-1))]
KeyError: '96'`

I used default setting in Tiled VAE:
Latent tile width/height: 96
Scale to 2X : 1024x1536
Model use： stablesr_webui_sd-v2-1-512-ema-000117
Upscaler(Tiled VAE): None.

For Mixture of Diffusers instruction in README, it returns:
`  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "D:\ai\auto-ui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\ai\auto-ui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\ai\auto-ui\extensions\sd-webui-stablesr\srmodule\spade.py", line 52, in _forward
    out *= (1 + self.mlp_gamma(actv).repeat_interleave(repeat_factor, dim=0))
RuntimeError: The size of tensor a (32) must match the size of tensor b (96) at non-singleton dimension 2
`

**Comment by pkuliyi2015** [comment]
Please try to set the Tiled Diffusion upscaler to None.

**Comment by mockinbirdy** [comment]
It gives KeyError: '64' no matter what settings you put in tiled diffusion or tiled vae.

**Comment by aetherwu** [comment]
> Upscaler(Tiled VAE): None.

I've provided it as above.

**Comment by pkuliyi2015** [comment]
Some other users meet the same problem. After test, they found it work by just updating the webui and the two extensions to the latest. Would you mind have a try?

**Comment by halr9000** [comment]
Working for me as per instructions.
