### ISSUE TITLE
StableSR + ControlNet tile not working

### ISSUE THREAD

**Issue by segalinc** [pkuliyi2015/sd-webui-stablesr#19]
I am trying to use StableSR + ControlNet tile but I get this error

`[StableSR] Target image size: 2560x1600
Loading model from cache: control_v11f1e_sd15_tile [a371b31b]
Loading preprocessor: tile_resample
preprocessor resolution = 64
Calling preprocessor tile_resample outside of cache.
  0%|                                                                                         | 0/20 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(kr91ndjnzcnd7da)', 0, 'grainy, (masterpiece:1.0), (extremely detailed:1.0), illustration, (jndstdbbg style) \n\n', 'easynegative, blurry, smooth, weird colors, jpeg artifacts, seams, black, dark, animals, creature, human, building, tree, fog, mist, glow, ((dark area)), DIRTY, MESSY, overdetailed, tiny white dot, blurry, pixel, noise, intricate detail, ugly, bad art, heavy detailed, (low quality, worst quality:1.4)', [], <PIL.Image.Image image mode=RGBA size=512x320 at 0x7FA72479D8E0>, None, None, None, None, None, None, 20, 1, 4, 0, 1, False, False, 1, 1, 10, 1.5, 0.35, 3795394654.0, -1.0, 0, 0, 0, False, 1, 512, 2048, 1, 0, 0, 32, 0, '', '', '', [], 11, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True, False, <controlnet.py.UiControlNetUnit object at 0x7fa725cdcd30>, <controlnet.py.UiControlNetUnit object at 0x7fa724988ac0>, <controlnet.py.UiControlNetUnit object at 0x7fa724797ee0>, <controlnet.py.UiControlNetUnit object at 0x7fa724960d90>, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Bilinear', False, 'Lerp', '', '', False, False, None, True, False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, True, -1.0, True, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', 'None', None, 1, 'None', False, False, 'PreviousFrame', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, None, None, False, 50, 'stablesr_webui_sd-v2-1-512-ema-000117.ckpt', 5, True, 'Wavelet', False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/img2img.py", line 176, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/scripts.py", line 441, in run
    processed = script.run(p, *script_args)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/extensions/sd-webui-stablesr/scripts/stablesr.py", line 248, in run
    result: Processed = processing.process_images(p)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/processing.py", line 729, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 291, in process_sample
    return process.sample_before_CN_hack(*args, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/extensions/sd-webui-stablesr/scripts/stablesr.py", line 223, in sample_custom
    samples = sampler.sample(p, x, conditioning, unconditional_conditioning, image_conditioning=p.image_conditioning)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 383, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 257, in launch_sampling
    return func()
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 383, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/mnt/csegalin/bg_anime_gen/env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/mnt/csegalin/bg_anime_gen/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 137, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "/mnt/csegalin/bg_anime_gen/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/mnt/csegalin/bg_anime_gen/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/mnt/csegalin/bg_anime_gen/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/extensions/sd-webui-stablesr/scripts/stablesr.py", line 97, in unet_forward
    return getattr(unet, FORWARD_CACHE_NAME)(x, timesteps, context, y, **kwargs)
  File "/mnt/csegalin/bg_anime_gen/code/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 587, in forward_webui
    return forward(*args, **kwargs)
TypeError: forward() takes from 2 to 4 positional arguments but 5 were given`

I am using all the settings as instructed in img2img. is StableSR not compatible with controlnet?

**Comment by pkuliyi2015** [comment]
Yes. StableSR cannot work with ControlNet model. They are different UNet manipulations, and work on different SD versions (1.5/2.1 model).
