### ISSUE TITLE
RuntimeError: The size of tensor a (1024) must match the size of tensor b (768) at non-singleton dimension 1

### ISSUE THREAD

**Issue by cgdreamer** [pkuliyi2015/sd-webui-stablesr#39]
大佬你好，我在放大一张725 x 878 图片到2倍时报了这个错误，主模型用的v2-1_768-ema-pruned sr模型用的webui_768v_139.ckpt，cfg=7,steps=20,采样用的euler a,也启用的Tiled Diffusion和分块 VAE,Tiled Diffusion升级到了最新版.请问是什么原因呢？
---
[StableSR] Target image size: 1456x1760
[Tiled Diffusion] ControlNet found, support is enabled.
[Tiled Diffusion] StableSR found, support is enabled.
Mixture of Diffusers hooked into 'Euler a' sampler, Tile size: 64x64, Tile batches: 4, Batch size: 8. (ext: ContrlNet)
[Tiled VAE]: input_size: torch.Size([1, 3, 1760, 1456]), tile_size: 1536, padding: 32
[Tiled VAE]: split to 2x1 = 2 tiles. Optimal tile size 1408x864, original tile size 1536x1536
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 1270 x 1536 image
[Tiled VAE]: Done in 2.116s, max VRAM alloc 5216.13d MB
*** Error completing request
*** Arguments: ('task(4bdixwtd7onc1qz)', 0, '(large breats,nsfw,bra),(8k, RAW photo, masterpiece:1.2), solo, full body,(hair accessories,night), (light on face:1.2), , floating hair,blush,eyelashes,Beautiful and delicate eyes, photorealistic, super detail, high quality, best quality', 'advertisement,paintings,3d, cartoon, anime, sketches,(worst quality:2),(low quality:2),(normal quality:2),lowres,normal quality,((monochrome)),((grayscale)),skin spots,NG_DeepNegative_V1_75T,pubic hair,glans', [], <PIL.Image.Image image mode=RGBA size=725x878 at 0x1CB6D357850>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.23, 4076662761.0, -1.0, 0, 0, 0, False, 0, 878, 725, 1, 2, 0, 32, 0, '', '', '', [], 11, False, {'ad_model': 'face_yolov8s.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, True, 'Mixture of Diffusers', False, True, 1024, 1024, 64, 64, 32, 8, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, True, 1536, 96, True, True, True, False, False, '', 0, False, 7, 98, 'Half Cosine Up', 3, 'Half Cosine Up', 3, 4, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None, 'Refresh models', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001CB6D2B9FF0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001CB6D2BA7D0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001CB6D313640>, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nBODY:1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1\nBODY0.5:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,1,1\nFACE0.2:1,0,0,0,0,0,0,0,0.2,0.6,0.8,0.2,0,0,0,0,0\nHAND:1,0,1,1,0.2,0,0,0,0,0,0,0,0,0,0,0,0\nCLOTHES:1,1,1,1,1,0,0.2,0,0.8,1,1,0.2,0,0,0,0,0\nPOSE:1,0,0,0,0,0,0.2,1,1,1,0,0,0,0,0,0,0\nPALETTE:1,0,0,0,0,0,0,0,0,0,0,0.8,1,1,1,1,1\nKEEPCHAR:1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,0,0\nKEEPBG:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,0,0\nREDUCEFIT:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nACT: 1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50, 'webui_768v_139.ckpt', 2, True, 'Wavelet', False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
    Traceback (most recent call last):
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\img2img.py", line 196, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\scripts.py", line 456, in run
        processed = script.run(p, *script_args)
      File "D:\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-stablesr\scripts\stablesr.py", line 248, in run
        result: Processed = processing.process_images(p)
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "D:\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\processing.py", line 729, in process_images_inner
        p.setup_conds()
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\processing.py", line 346, in setup_conds
        self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, self.negative_prompts, self.steps * self.step_multiplier, [self.cached_uc], self.extra_network_data)
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\processing.py", line 338, in get_conds_with_caching
        cache[1] = function(shared.sd_model, required_prompts, steps)
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\prompt_parser.py", line 143, in get_learned_conditioning
        conds = model.get_learned_conditioning(texts)
      File "D:\01-01HH\novelai-webui-aki-v3A\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
        c = self.cond_stage_model(c)
      File "D:\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\sd_hijack_clip.py", line 229, in forward
        z = self.process_tokens(tokens, multipliers)
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\sd_hijack_clip.py", line 254, in process_tokens
        z = self.encode_with_transformers(tokens)
      File "D:\01-01HH\novelai-webui-aki-v3A\modules\sd_hijack_open_clip.py", line 28, in encode_with_transformers
        z = self.wrapped.encode_with_transformer(tokens)
      File "D:\01-01HH\novelai-webui-aki-v3A\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 220, in encode_with_transformer
        x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
      File "D:\01-01HH\novelai-webui-aki-v3A\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 232, in text_transformer_forward
        x = r(x, attn_mask=attn_mask)
      File "D:\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\open_clip\transformer.py", line 154, in forward
        x = x + self.ls_1(self.attention(self.ln_1(x), attn_mask=attn_mask))
      File "D:\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\open_clip\transformer.py", line 151, in attention
        return self.attn(x, x, x, need_weights=False, attn_mask=attn_mask)[0]
      File "D:\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\01-01HH\novelai-webui-aki-v3A\extensions\a1111-sd-webui-locon\scripts\..\..\..\extensions-builtin/Lora\lora.py", line 425, in lora_MultiheadAttention_forward
        lora_apply_weights(self)
      File "D:\01-01HH\novelai-webui-aki-v3A\extensions\a1111-sd-webui-locon\scripts\..\..\..\extensions-builtin/Lora\lora.py", line 347, in lora_apply_weights
        self.in_proj_weight += updown_qkv
    RuntimeError: The size of tensor a (1024) must match the size of tensor b (768) at non-singleton dimension 1
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---

**Comment by cgdreamer** [comment]
换了一张图又没出问题了

**Comment by cgdreamer** [comment]
换了一张图又没出问题了
